version: '3.1'

services:  
  committeemicroservices:  
    image: "committeemicroservices:B${BUILD_NUMBER}"
    build:
      context: .
  integration:
    depends_on:
      - committeemicroservices
    image: "committeemicroservices:test-B${BUILD_NUMBER}"
    build:
      context: .
      dockerfile: Dockerfile.Integration
    
volumes:
    dbdata:
